### ISSUE TITLE
CSV with datetime values

### ISSUE THREAD

**Issue by matipazw** [mrodrig/json-2-csv#123]
## Background Information
- Module Version: ` `
- Node/Browser Version: ` `

The issue I'm reporting is with:
- [x ] json2csv
- [ ] csv2json

I have...
- [ ] searched to see if an issue has already been reported.
- [x ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [ ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Datetime fields with correct value in download doc.

## Actual Behavior

When the framework proccess a datetime, the final document contains the datetime using 00:00GMT instead of the local time.

## Data Sample 
CSV:
```csv

```

(or)

JSON:
```json

```

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');


```

**Comment by mrodrig** [comment]
Thanks for reporting this @matipazw!

I fixed the underlying issue and published `3.5.5` on NPM. Please let me know if you run into any other behavior that you don't expect. Thanks again!
