### ISSUE TITLE
CLI hangs instead of giving any error or result.

### ISSUE THREAD

**Issue by josh-hemphill** [mrodrig/json-2-csv#126]
## Background Information
- Module Version: `3.5.1 `
- Node/Browser Version: `Node 12.4.0 `

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

This is what I've been running ` json2csv response.json -o result.csv -S -A`

## Expected Behavior
Get some result

## Actual Behavior
New file is created, but CLI just hangs and no data is written to the file.

## Code Example
The json I'm trying to convert:
```json
{
	"LABOR_COSTS_SEGMENT": [
		{
			"LABOR_COST_RECORD": [
				{ "key":"value pairs"},
				{"each":"in their own object"}
			]
		},
		{
			"LABOR_COST_RECORD": [
				{ "key":"value pairs"},
				{"each":"in their own object"}
			]
		}
]}

```

**Comment by mrodrig** [comment]
Hi @josh-hemphill. Thanks for reporting this! Unfortunately, I can't seem to reproduce this locally using the JSON that you provided. I tried with both Node 10.9.0 and 12.6.0, but both are working for me using the command that you provided. I'm seeing the CSV get written to the file and the script returns and exits successfully. I'm not sure if maybe there's an issue with specifically Node 12.4.0? Would you mind updating to Node 12.6.0 to see if that fixes the issue you're seeing? Please let me know if you still are running into this issue and any additional info that you might be able to provide would be greatly appreciated.

![image](https://user-images.githubusercontent.com/2199972/60750147-32ddde00-9f72-11e9-9da3-efc36b9af5f2.png)

Vim of output contents: 
![image](https://user-images.githubusercontent.com/2199972/60750153-412bfa00-9f72-11e9-926f-1a6d639d6a8b.png)

**Comment by josh-hemphill** [comment]
I just tried running it in both cmd.exe and git bash after upgrading to node 12.6 and having the same issue.

**Comment by mrodrig** [comment]
Okay, thanks for giving that a try. I tried running it on my Windows machine with Node 12.6.0 and it works for me. If you happen to know where the module is installed, could you try running `node <path_to_node_modules>/json-2-csv/bin/json2csv.js <arguments>`? 

If that also hangs, then could you provide the verbose output when trying to run it like this: `NODE_DEBUG=* node <path_to_node_modules>/json-2-csv/bin/json2csv.js <arguments>` in case there's anything useful in the debug log that could indicate why it's hanging? `NODE_DEBUG=*` should essentially put node into verbose mode so that we can see what's happening.

**Comment by josh-hemphill** [comment]
Yep, node <path_to_node_modules>/json-2-csv/bin/json2csv.js <arguments> works much better. And NODE_DEBUG doesn't output anything unusual. I'm stumped.

**Comment by josh-hemphill** [comment]
Well, I found the issue... I installed the wrong package to my global packages... Sorry about that.

**Comment by mrodrig** [comment]
Oh, okay. No worries! Good to hear that it's working now. Please feel free to let me know if you notice anything else.
