### ISSUE TITLE
Using it as a head script import.

### ISSUE THREAD

**Issue by zarov** [mrodrig/json-2-csv#127]
## Background Information
- Module Version: `3.5.5`
- Node/Browser Version: `any browser`

The issue I'm reporting is with:
- [ ] json2csv
- [x] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [ ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [ ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior

I would like to use this library as a head script import.

## Actual Behavior

It fails as `require` is not a thing in browsers.

## Code Example
```html
<script src="https://cdn.jsdelivr.net/npm/json-2-csv@3.5.5/src/converter.min.js"></script>
```

## Question

Is there any way to achieve this without using `browserify`/`requirejs` or any library ? Are you open to have a version of the library that could be exported with all the things in it and don't need `require` ?

**Comment by mrodrig** [comment]
Hi @zarov. Thanks for reporting this. You're right - currently there isn't a way that I'm aware of that this library can be loaded into a browser via a <head> script import. I'm definitely open to supporting that, but I don't have any experience with converting NPM modules into browser-supported libraries. I'll take a look, but if someone beats me to it and creates a pull request for it, I'll definitely take a look at that too.
