### ISSUE TITLE
Code in examples is not working

### ISSUE THREAD

**Issue by fires3as0n** [mrodrig/json-2-csv#132]
## Background Information
- Module Version: ` 3.5.7`
- Node/Browser Version: `Node 10.16.0 `

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Code from exapmple copy-pasted to .js file executed by Node.js should work
https://github.com/mrodrig/json-2-csv/wiki/json2csv-Documentation#promise-example

## Actual Behavior
It throws an error: Error: A callback is required!

## Data Sample 
Look example from wiki, link is provided

## Code Example
Look example from wiki, link is provided

## Suggestion
Should call `converter.json2csv(documents)` be replaced by call to `converter.json2csvAsync(documents)`

**Comment by mrodrig** [comment]
Hi @fires3as0n. Sorry for the delay in getting back to you. You're right, that example is wrong. It should be json2csvAsync like you mentioned. I updated the wiki to reflect that, so it should be correct now. Thanks for reporting that and sorry for any inconvenience it may have caused!
