### ISSUE TITLE
csv2json duplicates nested key in the first column

### ISSUE THREAD

**Issue by juan-dura** [mrodrig/json-2-csv#139]
## Background Information
- Module Version: `3.5.9 `
- Node Version: ` v10.16.0`

The issue I'm reporting is with:
- [ ] json2csv
- [X] csv2json

I have...
- [x ] searched to see if an issue has already been reported.
- [x ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
[
 {
   "suj":{"codigo":137,"sexo":"M","edad":40,"fechaNacimiento\r":"5/17/1978\r"}
 },
  "suj":{"codigo":137,"sexo":"M","edad":40,"fechaNacimiento\r":"5/17/1978\r\n"}
 }
]    

## Actual Behavior
[
 {
   "﻿suj":{"codigo":137},
   "suj":{"sexo":"M","edad":40,"fechaNacimiento\r":"5/17/1978\r"}
 },
 {"﻿suj":{"codigo":137},
  "suj":{"sexo":"M","edad":40,"fechaNacimiento\r":"5/17/1978\r\n"}
 }
]    

## Data Sample 
CSV:
```
suj.codigo,suj.sexo,suj.edad,suj.fechaNacimiento
137,M,40,5/17/1978
137,M,40,5/17/1978
```

**Comment by mrodrig** [comment]
Hi @juan-dura. Thanks for reporting this. I tried to replicate this issue, but it seems to be outputting the expected JSON for me using the following code:

```javascript
'use strict';

let converter = require('json-2-csv');

const csv = 'suj.codigo,suj.sexo,suj.edad,suj.fechaNacimiento\n' +
    '137,M,40,5/17/1978\n' +
    '137,M,40,5/17/1978';

converter.csv2jsonAsync(csv)
    .then((json) => {
        console.log(json);
    })
    .catch((err) => {
        console.error('Error', err);
    });
```

Output:
```
$ node test-139.js 
[ { suj:
     { codigo: 137, sexo: 'M', edad: 40, fechaNacimiento: '5/17/1978' } },
  { suj:
     { codigo: 137, sexo: 'M', edad: 40, fechaNacimiento: '5/17/1978' } } ]

$ node -v 
v10.16.0


Are there any options that you're passing to csv2json? If so, could you provide them.
Thanks!

**Comment by juan-dura** [comment]
Sorry. My mistake. I am reading a CSV file. An I didn't notice that `fs.readFileSync` adds a space in the first key: `' suj.codigo,suj.sexo,suj.edad,suj.fechaNacimiento\n'`

I have to investigate why `fs.readFileSync` adds an space.

This is the file:
[test.txt](https://github.com/mrodrig/json-2-csv/files/4197219/test.txt)

This is my code:
```
'use strict';
let fs = require('fs');
let converter = require('json-2-csv');

const path = /test.txt";

const csv = fs.readFileSync(path, 'utf8');
console.log(csv);

converter.csv2jsonAsync(csv)
    .then((json) => {
        console.log(json);
    })
    .catch((err) => {
        console.error('Error', err);
    });
```

**Comment by mrodrig** [comment]
No worries! Great question - I tried your code with test.txt on my machine and it doesn't appear to be adding the space in so I'm really not sure why it's doing that for you.  Here's the output I'm seeing:

```
$ cat test.txt 
suj.codigo,suj.sexo,suj.edad,suj.fechaNacimiento
137,M,40,1978-05-17T00:00:00
137,M,40,1978-05-17T00:00:00
$ 
$ node test-139.js 
suj.codigo,suj.sexo,suj.edad,suj.fechaNacimiento
137,M,40,1978-05-17T00:00:00
137,M,40,1978-05-17T00:00:00

[ { suj:
     { codigo: 137,
       sexo: 'M',
       edad: 40,
       fechaNacimiento: '1978-05-17T00:00:00' } },
  { suj:
     { codigo: 137,
       sexo: 'M',
       edad: 40,
       fechaNacimiento: '1978-05-17T00:00:00\n' } } ]
```
