### ISSUE TITLE
appending BOM unexpectedly

### ISSUE THREAD

**Issue by ronyeh3** [mrodrig/json-2-csv#145]
## Background Information
- Module Version: `latest `
- Node/Browser Version: `10 `

The issue I'm reporting is with:
- [ x] json2csv
- [ ] csv2json

I have...
- [ ] searched to see if an issue has already been reported.
- [ ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [ ] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
should add BOM only to header

## Actual Behavior
In some point in my code im changinf the options to prependHeader=false
and im appending rows succsfully without the header
but sometimes (rarely)
json2csv still add unexpected BOM when im appending csv rows ,even with prependHeader=false
## Data Sample 
CSV:
```csv

```

(or)

JSON:
```json

```

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');


```

**Comment by mrodrig** [comment]
Thanks for reporting that @ronyeh3. Could you please provide some example so I can reproduce the issue? I can't seem to replicate this so it would be helpful to see how you're getting it to happen.

**Comment by mrodrig** [comment]
Closing the issue because I can't reproduce this without a code example. If you have a chance to create an example so I can reproduce this issue, please feel free to reopen the issue. Thanks!
