### ISSUE TITLE
not parsing wrapped delimiter in first column

### ISSUE THREAD

**Issue by pustovitDmytro** [mrodrig/json-2-csv#153]
## Background Information
- Module Version: `3.7.3 `
- Node/Browser Version: ` node v8.11.1`

The issue I'm reporting is with:
- [ ] json2csv
- [x] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
a comma (delimiter) can be placed in first column.
[ { 'column 1': 'A,B', 'column 2': 'C,D', 'column 3': 'E,F' } ]

## Actual Behavior
[ { 'column 1': '"A', 'column 2': 'B"', 'column 3': 'C,D' } ]

## Data Sample 
CSV:
```csv
column 1,column 2,column 3
"A,B","C,D","E,F"
```
(crlf line breaks used)

## Code Example
```javascript
import { csv2jsonAsync } from 'json-2-csv';

const headers = [ 'column 1', 'column 2', 'column 3' ];
const csvopts = {
        delimiter : {
            field : ',',
            eol   : '\r\n'
        },
        keys : headers
    };

const fileData = await fs.readFile(filePath, 'UTF-8');
const data =  await csv2jsonAsync(fileData, csvopts);
```
In second and third columns delimiter is parsed correctly

**Comment by pustovitDmytro** [comment]
looks like I've found a possible solution, I'll try to provide PR with test

**Comment by mrodrig** [comment]
Thanks for reporting that and for the PR @pustovitDmytro! Good find. Your PR looks great. I'm going to merge it in and publish it on NPM in `3.7.4`.
