### ISSUE TITLE
[CSV -> JSON] An empty value at the end of the CSV does not write to JSON properly.

### ISSUE THREAD

**Issue by Bakabake** [mrodrig/json-2-csv#155]
## Background Information
- Module Version: `3.7.4`
- Node/Browser Version: `10.16.0`

The issue I'm reporting is with:
- [ ] json2csv
- [X] csv2json

I have...
- [X] searched to see if an issue has already been reported.
- [X] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [X] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
If there exists an empty element as the very last entry of the CSV, an empty value should be written out.

## Actual Behavior
The last field does not get written out, and the previous element has a comma appended to the end of the value.
Using the csv/code below, the output will be:
```json
[{ "data": { "uid":"my_uid," } }]
```

## Data Sample 
CSV:
```csv
data.uid,data.name
my_uid,
```

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');

converter.csv2jsonAsync(csv)
    .then(json => { console.log(JSON.stringify(json)) })

```

## Additional Notes
I've noticed that consecutive empty values also cause the same issue.  
Use the above test code with the following csv:
```csv
data.uid,data.name
,
```
The resulting JSON will look like:
```json
[{ "data":{ "uid": "," }}]

```

Multiple empty rows produce proper output except for the last row:
```csv
data.uid,data.name
,
,
```
Results in:
```json
[ { "data":{ "uid": "", "name": "" } },
  { "data":{ "uid": "," } }]
```

Also, if the last element is not empty, everything works fine.
Using this csv:
```csv
data.uid,data.name,data.desc
my_uid,,
my_other_uid,,test
```
Produces the appropriate JSON:
```json
[ {"data":{"uid":"my_uid",
                "name":"",
                "desc":""}},
  {"data":{"uid":"my_other_uid",
                "name":"",
                "desc":"test"}}]
```

**Comment by mrodrig** [comment]
Thanks for reporting this @Bakabake. Another good find. I have a PR out to handle that scenario and will merge it in once the tests finish running. I should have it published to NPM in a little bit as `3.7.5`. Thanks again for reporting it and for all of the additional notes you provided. They were really helpful.

**Comment by Bakabake** [comment]
Anytime!  I'm always happy to help!

**Comment by dilshansdoq** [comment]
I am facing a similar issue to this.
Input: `sender_id,receiver_id,message,image\r\nu1,"u2","m1",\r\nu1,"u3","m2",`
Expected Output: 
```
[
          { sender_id: 'u1', receiver_id: 'u2', message: 'm1', image: '' },
          { sender_id: 'u1', receiver_id: 'u3', message: 'm2', image: '' },
]
```
Actual Output:
```
[
          { sender_id: 'u1', receiver_id: 'u2', message: 'm1', image: '' },
          { sender_id: 'u1', receiver_id: 'u3', message: 'm2', image: ',' },
]
```

Code:
```
const parsed = csvParser.csv2json(data, {
  trimFieldValues: true,
  trimHeaderFields: true,
});
```

So the issue occurs when at the end of nth row, there is no line break(lf or crlf), and the (m-1)st column has quoted string.

Please let me know if you require a minimum reproduction code. I will create a separate issue then.
