### ISSUE TITLE
'unwindArrays' does not exist in type 'IFullOptions'

### ISSUE THREAD

**Issue by nalvarezdiaz** [mrodrig/json-2-csv#158]
## Background Information
- Module Version: `3.7.5 `
- Node/Browser Version: ` v12.14.0`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [ ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
`json2csvAsync` should accept `unwindArrays` as option.

## Actual Behavior
`options` doesn't accept `unwindArrays` property because this property isn't declared as part of `IFullOptions` or it extended interface `ISharedOptions`

## Code Example
```typescript
import { json2csvAsync } from 'json-2-csv'

async function (jsonObj: {}): Promise<void> {
    const csv = await json2csvAsync(
        [ jsonObj ],
        { unwindArrays: true }, // 'unwindArrays' does not exist in type 'IFullOptions'
    )
}
```

**Comment by mrodrig** [comment]
Thanks for reporting this @nalvarezdiaz. It looks like `unwindArrays` and `useLocaleFormat` were both missing from the options specified for TypeScript support. Sorry about that. I've published a fix for that in `3.7.6`.
