### ISSUE TITLE
Customized Header Names

### ISSUE THREAD

**Issue by kentsitu** [mrodrig/json-2-csv#183]
## Background Information
- Module Version: ` 3.11.1`
- Node/Browser Version: ` V12.18.0`

The issue I'm reporting is with:
- [! ] json2csv

I have...
- [! ] searched to see if an issue has already been reported.
- [! ] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [ !] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Customized header names configuration should be available next to keys  in option object

## Actual Behavior
Not such configuration in option.

**Comment by mrodrig** [comment]
Hi @kentsitu, thanks for opening this. If I'm understanding correctly, you're looking to be able to specify a custom header for a particular CSV column, right? If so, that is currently supported. Here's the relevant snippet from the `README.md`:
  * `keys` - Array - Specify the keys that should be converted.
    * Default: These will be auto-detected from your data by default.
    * Keys can either be specified as a String representing the key path that should be converted, or as an Object with the `field` property specifying the path. When specifying keys as an Object, you can also optionally specify a `title` which will be used for that column in the header. The list specified can contain a combination of Objects and Strings. 
      * `[ 'key1', 'key2', ... ]`
      * `[ { field: 'key1', title: 'Key 1' }, { field: 'key2' }, 'key3', ... ]`

Support for this was added in #171 and I have a code example in a comment here: https://github.com/mrodrig/json-2-csv/issues/171#issuecomment-739133307

Hope this helps.

**Comment by kentsitu** [comment]
HI @mrodrig , that's what I was looking for. It's working. Thank you very much!
