### ISSUE TITLE
Wrong CSV

### ISSUE THREAD

**Issue by JeffersonLupinacci** [mrodrig/json-2-csv#192]
## Background Information
- Module Version: `^5.0.6`
- Node/Browser Version: ` 10`

The issue I'm reporting is with:
- [X] json2csv
- [ ] csv2json

I have...
- [X] searched to see if an issue has already been reported.
- [X] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [X] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior

"activo","tipo","validity_ts"
1,"Superfície","2021-02-11T10:13:17.681Z"
1,"Superfície","2021-02-11T09:38:20.766Z"

## Actual Behavior

"activo","tipo","validity_ts"
1,"Superfície
","2021-02-11T10:13:17.681Z"
1,"Superfície
","2021-02-11T09:38:20.766Z"

## Data Sample 
CSV:
```csv
"activo","tipo","validity_ts"
1,"Superfície
","2021-02-11T10:13:17.681Z"
1,"Superfície
","2021-02-11T09:38:20.766Z"
1,"Superfície
","2021-02-11T09:53:17.643Z"
1,"Superfície
","2021-02-11T09:58:21.551Z"
1,"Superfície
","2021-02-11T11:08:18.709Z"
1,"Superfície
","2021-02-11T11:03:19.028Z"
1,"Superfície
","2021-02-11T11:18:17.073Z"
1,"Superfície
","2021-02-11T11:33:17.244Z"
1,"Superfície
","2021-02-11T14:58:16.227Z"
1,"Superfície
","2021-02-11T15:08:16.150Z"


```
JSON:
```
{
    "resultset": [
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T16:38:33.655Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T16:53:33.758Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:03:35.645Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:08:35.337Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:28:33.305Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:38:33.617Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:33:33.477Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:58:33.353Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T17:48:33.272Z"
        },
        {
            "activo": 1,
            "tipo": "Superfície\r\n",
            "validity_ts": "2021-04-04T18:33:33.226Z"
        }
    ]
}

```

## Code Example
```javascript
// Please include a simple example to replicate the issue
const parser = new Parser();
const csv = parser.parse(promise.resultset);

```

**Comment by mrodrig** [comment]
Hi @JeffersonLupinacci. Please double check that you're using the `json-2-csv` module. I believe you may be using the `json2csv` module by a different author since this module doesn't have a `Parser` class that's used for the conversion.

For what it's worth, this module (`json-2-csv`) is generating RFC-4180 compliant CSV for the provided JSON.

Please feel free to re-open if the issue you're encountering is in fact with this module.
