### ISSUE TITLE
Safari - Invalid Regular Expression - Invalid Group Specifier Names

### ISSUE THREAD

**Issue by CodesAreHonest** [mrodrig/json-2-csv#197]
## Background Information
- Module Version: `3.14.0`
- Node/Browser Version: `16.1.0`

The issue I'm reporting is with:
- [x] json2csv
- [x] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior

- The library should works in Safari browser in MacOS and iOS.

## Actual Behavior
![Screenshot 2021-06-11 at 3 28 55 PM](https://user-images.githubusercontent.com/25884538/121648136-be9b0600-cac9-11eb-90c8-baf41b24c14f.png)

The browser complains the error (refer screenshot above) due to [Lookbehind Regex does not support in Safari](https://caniuse.com/js-regexp-lookbehind). 

## Discussion

The library use `doc-path` as dependencies.
Refer this [line](https://github.com/mrodrig/doc-path/blob/stable/lib/path.js#L104), the function `state` use Negative Lookbehind Regex to perform `exec` leads to the mentioned errors and break in the browser.

**Comment by mrodrig** [comment]
Thanks for reporting this @CodesAreHonest. I'll work on getting a fix out for this very soon. I'll post back with an update once I have a new release published to NPM that fixes this.

**Comment by CodesAreHonest** [comment]
Appreciate your response on this issue, looking forward for the fixes and thanks for the awesome library !

**Comment by mrodrig** [comment]
Thanks again for reporting this @CodesAreHonest. The fixed version should be up on NPM now as version `3.14.1`. Please feel free to let me know if you run into any other issues.

**Comment by CodesAreHonest** [comment]
My pleasure to help, the latest version work like charm in the Safari environment. 

Much appreciated.
