### ISSUE TITLE
Flattening of Array to comma separated values?

### ISSUE THREAD

**Issue by cstrat** [mrodrig/json-2-csv#200]
If I have a JSON object with the following data:

```
{
  "Name": "test",
  "Tags": ["A", "B", "C"],
}
```

Converting this to CSV I'd like it to look like this:

```
Name,Tags
test, "A,B,C"
```

It's easy enough to manipulate the data prior to sending it to `json-2-csv`, but not sure if there are any plans for custom data hooks/manipulation.

**Comment by mrodrig** [comment]
Hi @cstrat. Thanks for asking. Currently the only data manipulation hook that's implemented for the `json2csv` method is the `parseValue` function type option. If you pass a function in using that key in the options object, you'll be able to manipulate the specific field value that's passed to the provided `parseValue` function. For example:

```javascript
import converter from 'json-2-csv';

const csv = await converter.json2csvAsync([
    {
        "Name": "test",
        "Tags": ["A", "B", "C"],
      }
], {
  parseValue: (value) => {
      if (Array.isArray(value)) {
        return value.join(',');
      }
      return value;
  }
});

console.log(csv);
```

This overrides the default field value conversion method that's included in the module, and can be found here: https://github.com/mrodrig/json-2-csv/blob/stable/lib/json2csv.js#L316

Are there other data manipulation hooks that you think would be beneficial?

**Comment by cstrat** [comment]
Thanks for the response!
I wasn't looking close enough at the docs to notice that.

I'm using a different CSV to JSON converter (csvtojson) which has hooks based on CSV header so I was hoping this had something similar based on a JSON attribute, but this is all I really need.
