### ISSUE TITLE
Problem with list of objects same keys

### ISSUE THREAD

**Issue by mebibou** [mrodrig/json-2-csv#207]
## Background Information
- Module Version: `3.14.4`
- Node/Browser Version: `12.22.6`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

When doing the following:
```javascript
json2csv([{
  list: [{
    a: 1
  }, {
    a: 2
  }]
}], {
  expandArrayObjects: true
})
```
The current resulting csv is:
```csv
list.a
[1,2]
```
which looks like you had instead:
```
[{
  list: [{
    a: [1, 2]
  }]
}]
```
But the CSV could actually reflect the original structure if it was like this instead:
```
list.0.a,list.1.a
1,2
```
I understand some might want the first result, but it would be nice to have an option to have a more like-to-like representation?

**Comment by mrodrig** [comment]
Thanks for reporting this @mebibou. I can definitely see this as being useful as well, especially if converting back to JSON from CSV is a requirement. I'll take a look at how I could make this work with the existing `json2csv` options.

**Comment by JoaoLucasFurtadoa** [comment]
Tank You guys. Congulations!

**Comment by whaaaley** [comment]
I just ran into this issue as well. It would be great to have! :D

**Comment by sofakingworld** [comment]
Same requirement, it would be useful feature to me

**Comment by Previesam** [comment]
Hi, Thank you for the great work here @mrodrig. Looking at this I can see some which may not have been accounted for. 

Is this supported in CLI?

Does it work the other way round when converting csv to json? like a csv with key test.list.0 would it be interpreted as an array as well? This does not seem to be the case on the CLI.

I really need to be able to consistently convert from csv to json and reverse without any issue.

So just like this arrays indexes will be used as keys and in converting csv2json the same will be intepreted back to array.
