### ISSUE TITLE
Headerless CSV

### ISSUE THREAD

**Issue by vferdiansyah** [mrodrig/json-2-csv#211]
This library still doesn't support CSV file without header does it? Or did I miss something?
Would love to submit a PR for this feature if it's still not supported.

**Comment by mrodrig** [comment]
Hi @vferdiansyah. I think you might be looking for the `prependHeader` option which can be set to `false` for `json2csv`/`json2csvAsync` to exclude the auto-generated header line, but if not, then I'm definitely open to PRs! Thanks!

**Comment by vferdiansyah** [comment]
@mrodrig it's actually for `csv2json`/`csv2jsonAsync` since i'm converting CSV to JSON. What I meant was something like this:
```
RH|911|20211007
SH|ATMB-000|RPT_DATE|TR_DATE|TR_TIME|ACQ_ID|ISS_ID|BNF_ID|BNF_MBR_ID|FWD_ID|TRML_ID|TRML_CD|CARD_NUMBER|FROM_ACCT_NBR|TRAN_CODE|REV|DB|CR|AMOUNT|XRATE|DB_RC|CR_RC|ISS_TRACE_NBR|BNF_TRACE_NBR|REF_NBR|RECEIPT_NBR|TO_ACCT_NBR|CUST_REF_NBR|ACQ_FEE|BNF_FEE|SW_FEE
SB|ATMB-000|20211007|211006|000139|542|542|911|||JG8888|6017|6391696049177670|109249177670|4010|||C|100000|||00||002706|21278W005581|432584|085283259790||3570|1500|1430
SB|ATMB-000|20211007|211006|000152|911|911|13|||71922654|6017|636351081371922654|081371922654|4010|||C|20000|||00||010585|097129083138|207388|898082269749149|2310906974788916|3570|1500|1430
```
In the sample file above since the first line only consists of 3 columns, `csv2json`/`csv2jsonAsync` will only treat the rest of the data as a 3 column CSV even though looking from the second line (the actual header), it actually has more than 3 columns. I would like to be able to choose the second line as the header (or probably any line if there're use cases for it).

As far as my understanding goes of this library, it's not possible at the moment. Could you give me a hint on where should I start if I wanted to submit a PR for this feature?

**Comment by mrodrig** [comment]
@vferdiansyah Thanks for your patience. You're right - that use case isn't currently supported, but I could see it as potentially being useful in some cases, like the example you provided. Unfortunately, I don't currently have time to devote to this, but I'd be open to a PR for it. One thing that I'd be interested in, is whether the _n_ lines leading up to the header would still be converted, or if they should simply be discarded. If they're being discarded, then it might be simpler to manipulate the contents prior to passing them to `csv2json`, but I'm probably missing some nuances of the use case.

I think the `/lib/csv2json.js` file would be the best place to start.

The `convert` function at the bottom of the file specifies the main function logic flow.
https://github.com/mrodrig/json-2-csv/blob/stable/lib/csv2json.js#L383-L394
```javascript
    function convert(data, callback) {
        // Split the CSV into lines using the specified EOL option
        // validateCsv(data, callback)
        //     .then(stripExcelBOM)
        stripExcelBOM(data)
            .then(splitCsvLines)
            .then(retrieveHeading) // Retrieve the headings from the CSV, unless the user specified the keys
            .then(retrieveRecordLines) // Retrieve the record lines from the CSV
            .then(transformRecordLines) // Retrieve the JSON document array
            .then((params) => callback(null, params.json)) // Send the data back to the caller
            .catch(callback);
    }
```

One of the calls specified there is the `retrieveHeading` function, which is what currently just pulls the first line from the CSV input and then generates some metadata around it.
https://github.com/mrodrig/json-2-csv/blob/stable/lib/csv2json.js#L32-L35
```javascript
    function retrieveHeading(lines) {
        let params = {lines},
            // Generate and return the heading keys
            headerRow = params.lines[0];
```
