### ISSUE TITLE
Custom sorting of headers

### ISSUE THREAD

**Issue by mebibou** [mrodrig/json-2-csv#216]
## Background Information
- Module Version: `3.14.4`
- Node/Browser Version: `12.22.6`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

It would be useful to be able to use a function rather than just a boolean for the `sortHeader` option. So it would look like

```javascript
{
  sortHeader: (a, b) => 1
}
```
So like a typical javascript sort function

**Comment by mrodrig** [comment]
Thanks for reporting this @mebibou. That's a great idea and a very nice feature to have. Thanks for the PR too!

**Comment by mrodrig** [comment]
Released on NPM as `3.16.0`. Thanks again!
