### ISSUE TITLE
How to properly change mongoDB timestamp to proper date?

### ISSUE THREAD

**Issue by smammadov1994** [mrodrig/json-2-csv#219]
I want to go from this:
2022-02-01T16:17:16.233Z

to this:

02/01/2022

How exactly do I parse this data using this library and make sure it appears as needed when excel opens the file?

**Comment by mrodrig** [comment]
Hi @smammadov1994. Good question. It looks like mongoDB returns values stored as dates in the database as a Date object based on my testing, so you should be able to use the `parseValue` option to specify a custom parser which formats dates values how you would like them to appear.

For example:
```
   return converter.json2csvAsync(json, {
        parseValue: (value, defaultParser) => {
            if (value instanceof Date) {
                return value.toLocaleDateString('en-US'); // convert to MM/DD/YYYY format
            }
            return defaultParser(value);
        }
    });
```
