### ISSUE TITLE
Comma in data not handled

### ISSUE THREAD

**Issue by hutch120** [mrodrig/json-2-csv#22]
Hi, great utility... I hope I'm not missing something obvious, but, it doesn't seem to handle commas in the CSV data during import even when there are double quotes on fields.

E.g. Take this CSV data where the data with a comma has double quotes.
header1,header2,header3
row1 column1,"row1 column2, with comma", row1 column3
row2 column1,row2 column2, row2 column3

This turns into the following JSON using csv-2-json and we loose row1 column3. 
[{
	"header1" : "row1 column1",
	"header2" : "row1 column2",
	"header3" : "with comma"
}, {
	"header1" : "row2 column1",
	"header2" : "row2 column2",
	"header3" : "row2 column3"
}]

Worse still, if this is in the middle somewhere, the data pushes all other fields down.

http://en.wikipedia.org/wiki/Comma-separated_values

Again, great utility, but would be pretty much perfect with this modification.

**Comment by mrodrig** [comment]
Thanks for reporting this.  After going through and cleaning up the code and tests recently I realized that csv2json is not currently supporting the options.DELIMITER.WRAP (quoting of field values).  It was implemented in json2csv back in #3.

I've been looking into this and I know I can definitely add support for CSV strings that always have the values wrapped in the options.DELIMITER.WRAP value, but it's a bit more difficult to handle the case where some values are wrapped and others aren't.  I pushed my changes/investigation code up to  the csv2json-wrap-fix branch.  It isn't complete, but it's a start.  If you have any suggestions or want to try implementing this, feel free to open a pull request.  I'll keep looking into solutions, but I can't give a definitive date as to when I think I'll have this fixed.  Hopefully this week or next week though.

**Comment by mrodrig** [comment]
I've been playing around with this quite a bit and think I have a good working solution.  I need to clean it up a bit, but I'm hoping to have it merged in and published in 1.3.0 some time tomorrow.

**Comment by hutch120** [comment]
Fantastic! Will test when it is ready.

**Comment by mrodrig** [comment]
Just published 1.3.0 which should fix this.  If you run into any issues, please let me know.  Thanks!

**Comment by hutch120** [comment]
Champion, I have tested import (csv-2-json) and it is working perfectly!!! :) 

Are you able to fix the export also? json-2-csv has the same problem.

**Comment by mrodrig** [comment]
Thanks! Glad to hear csv-2-json is working as expected!  I'm not familiar with the json-2-csv problem -  Is it not properly wrapping the values in the output?

**Comment by hutch120** [comment]
Hi Mike,

Thanks for the quick response. The problem is as follows.

Take this typically JSON object, where there is a comma in the address field:
{
	"Name" : "John Smith",
	"Address" : "13 Mary Street, Smithville",
	"Phone" : "123456789"
}

The output from this using json-2-csv is as follows:

Name,Address,Phone
John Smith,13 Mary Street, Smithville,123456789

There are now 3 headers and four data elements. The comma in the data makes this invalid CSV without escaping it with quotes. Further it cannot be imported using csv-2-json.

Cheers,
Simon

**Comment by mrodrig** [comment]
Thanks for the example, Simon.  Right now the module defaults to no field wrapping which will definitely run into issues when there is a quote in the data.  If you set the json2csv call's options to have `options.DELIMITER.WRAP` set to `'"'` (a double quote) that will fix the issue that occurs when the data has a comma in it.  The csv2json import should work properly on the output from json2csv if the options.DELIMITER.WRAP field is set to the same value that was used.

So for example the csv2jsonCallback will print out the same JSON that was originally passed in:
```javascript
var converter = require('json-2-csv');

var documents = [
    {
        "Name" : "John Smith",
        "Address" : "13 Mary Street, Smithville",
        "Phone" : "123456789"
    }
];

var options = {DELIMITER: {WRAP: '"'}};

var csv2jsonCallback = function (err, json) {
    if (err) throw err;
    console.log('JSON\n', json);
};

var json2csvCallback = function (err, csv) {
    if (err) throw err;
    console.log('CSV\n', csv);
    converter.csv2json(csv, csv2jsonCallback, options);
};

converter.json2csv(documents, json2csvCallback, options);
```

In a future release I think I might change the options to default to have `options.DELIMITER.WRAP` set to `'"'` (double quote) to be safe and prevent this issue.

Thanks,
Mike

**Comment by hutch120** [comment]
Ah, of course!! Thanks. Works perfectly... including "escaping" the delimiter :)

I agree, turning on double quotes as the delimiter by default makes sense.
