### ISSUE TITLE
sync version

### ISSUE THREAD

**Issue by Nokel81** [mrodrig/json-2-csv#238]
I noticed #29, however looking at the code there are no actual uses of `await` anywhere.

Would you be open to a PR that removes all `async/await` and `Promises`?

Given that you are not doing anything asynchronous it doesn't help and actually is a barrier because this library cannot be used in synchronous environments.

**Comment by mrodrig** [comment]
Hi @Nokel81! Sorry for the delay in getting back to you on this. I just realized my Outlook app wasn't syncing and realized I missed quite a few emails/notifications. Thanks for the PR to add that functionality back in. I had removed the explicitly synchronous methods at one point for simplicity, but it makes sense that it could limit where this might be possible to use. I'll try to review the PR in tomorrow after work and will merge it in and get a new release out with any `npm audit fix` updates that may be needed. Thanks!

**Comment by mrodrig** [comment]
Released 5.0.0. Thanks again for the PR!
