### ISSUE TITLE
Need Ability to Repress Header

### ISSUE THREAD

**Issue by spxis** [mrodrig/json-2-csv#24]
Hi there,

Excellent utility that I use with Bluebird Promises. I moved from the "json2csv" because you support promises. That said, that library had the option to not include (or repress) the header row (first line) from the CSV output. I've read through the documentation and code and do not see this option...

For now, I just remove the first line and use the library as-is without making any modifications. 

Is this something you can provide support for? If not, should I fork, implement and pull request?

**Comment by mrodrig** [comment]
Thanks for reporting this. Just implemented the ability to repress the header via the ```PREPEND_HEADER``` option in 1.2.1.

**Comment by spxis** [comment]
Wow! You're quick!!! I literally wrote this up before bed and you've already tested and fixed before I woke up lol. I'll get a latest and confirm the fix on my end as well...

**Comment by spxis** [comment]
I have confirmed that this fix works very well. Thank you once again.
