### ISSUE TITLE
Incorrect parsing of wrapped values when the new line is right after the starting quote

### ISSUE THREAD

**Issue by symbianm** [mrodrig/json-2-csv#240]
## Background Information
- Module Version: `4.1.0`
- Node/Browser Version: `node v18.17.1`

The issue I'm reporting is with:
- [ ] json2csv
- [x] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Quoted values split across multiple lines should be correctly parsed. 

## Actual Behavior
The parser behaves incorrectly when the new line is right after the starting quote.

## Data Sample 
CSV:
```csv
"User","Rental","City","State","ZipCode","Lead","Created","Qualified","Notes","Status","Details","Rating","Feedback","External Id"
"Leasing  Team","xxxxx North Sabre Drive","San Tan Valley","AZ","85142","AaronMiriam McAlpine","10/1/2023 5:25 PM MST","10/1/2023 5:27 PM MST","","Confirmed","10/1/2023 5:30 PM MST","5","
Layout was nice. Landscape needed work. But nice otherwise.","a001K00000vxWbxxxx"

```

## Code Example
```javascript
const fs = require('fs');
const { csv2json } = require('json-2-csv');

(async () => {
  const contentString = fs.readFileSync('test.csv');
  const jsonData = await csv2json(contentString.toString(), {
    parseValue: (fieldValue) => fieldValue, // stop converting values
  });
  console.log(jsonData);

  // Result
  // [
  //   {
  //     User: 'Leasing  Team',
  //     Rental: '34517 North Sabre Drive',
  //     City: 'San Tan Valley',
  //     State: 'AZ',
  //     ZipCode: '85142',
  //     Lead: 'AaronMiriam McAlpine',
  //     Created: '10/1/2023 5:25 PM USMST',
  //     Qualified: '10/1/2023 5:27 PM USMST',
  //     Notes: '',
  //     Status: 'Confirmed',
  //     Details: '10/1/2023 5:30 PM USMST',
  //     Rating: '5',
  //     Feedback: '',
  //     'External Id': undefined
  //   },
  //   {
  //     User: 'Layout was nice. Landscape needed work. But nice otherwise."',
  //     Rental: 'a001K00000vxWbFQAU',
  //     City: undefined,
  //     State: undefined,
  //     ZipCode: undefined,
  //     Lead: undefined,
  //     Created: undefined,
  //     Qualified: undefined,
  //     Notes: undefined,
  //     Status: undefined,
  //     Details: undefined,
  //     Rating: undefined,
  //     Feedback: undefined,
  //     'External Id': undefined
  //   }
  // ]
})();
```

[test.csv](https://github.com/mrodrig/json-2-csv/files/12840089/test.csv)
<img width="526" alt="Screenshot 2023-10-08 at 9 59 27" src="https://github.com/mrodrig/json-2-csv/assets/3383599/7432e84d-6f92-4fe7-9aa5-3fd545fc0440">

**Comment by mrodrig** [comment]
Thanks for reporting this @symbianm! I can confirm that this was a bug that was present in the CSV parsing logic when an EOL delimiter (typically newline) appeared inside a field (typically quotes) delimited value. This issue is resolved now in version `5.0.1`. Please let me know if you run into any other issues.
