### ISSUE TITLE
Providing option.keys[] field with RegExp throws kp.slice() is not a function

### ISSUE THREAD

**Issue by dwarthen-tnn** [mrodrig/json-2-csv#251]
## Background Information
- Module Version: `5.4.0 `
- Node/Browser Version: ` node 18.17.1`

The issue I'm reporting is with:
- [X] json2csv
- [ ] csv2json

I have...
- [X] searched to see if an issue has already been reported.
- [X] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [X] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Expected Behavior
Supply `keys` with a finite set of field values that I know will be present and want to re-map, plus one catch-all field, eg. `new RegExp(/./, g)` which should direct json-2-csv to re-map those fields and keep all others the same.

## Actual Behavior

for any RegExp I've tried, received 
```
\node_modules\doc-path\lib\path.js:122 
        key: kp.slice(0, dotIndex >= 0 ? dotIndex : undefined).replace(/\\./g, '.'),
                ^

TypeError: kp.slice is not a function
    at state (.\node_modules\doc-path\lib\path.js:122:17)
    at evaluatePath (.\node_modules\doc-path\lib\path.js:17:42)
```

## Data Sample 

JSON:
```json
[
{
 "a":1,
 "b":2,
 "c":3,
 "25s346dfgd":4,
 "eyu3":5,
 "sd":6
},
{
 "a":1,
 "b":2,
 "c":3,
 "as9a":4,
 "345asfdh8":5,
 "13sd":6
}
]
```

## Code Example
```javascript
// Please include a simple example to replicate the issue
let converter = require('json-2-csv');
converter.json2csv(data, {
  keys : [
                     {
                         "field": 'a',
                         "title": 'A'
                     },
                     {
                         "field": 'b',
                         "title": 'B'
                     },
                     {
                         "field": 'c',
                         "title": 'C'
                     },
                     {
                         "field": /./, /** or /as9a/ or /[A-Za-z]/ or new RegExp('.',g) or any other permutation of a valid JS RegExp object. **/
                         "wildCardMatch": true
                     },
     ]
});

```

I tried {field": '', "wildCardMatch": true } which creates one new column with the name given by "field" and no data. Leaving off the fourth key entirely likewise ensures that only the three keys specified will make it into the output file.

I have a handful of possible columns that I know will start with H, but { "field": 'H', "wildCardMatch" : true} does the same thing: creates column 'H' and fills it with undefined rows.

Thanks

**Comment by mrodrig** [comment]
Hi @dwarthen-tnn, thanks for reporting this. The error that you're seeing (`TypeError: kp.slice is not a function`) is because the package doesn't currently support any RegExps in the `keys` option. As noted in the README, the `keys` option currently just supports either an array of strings or objects in this format:

```javascript
{
  "field": string, // required
  "title": string, // optional
  "wildcardMatch": boolean, // optional - default: false
}
```

If I'm understanding your use case correctly, you're essentially looking for a way to specify a custom title for some keys while still including all of the auto-detected keys in the generated CSV. Is that accurate? If so, I think this should be possible to support by refactoring how the titles are specified. That seems like it's probably the best way to handle this type of use case, and could also be setup to handle the title prefixing for `wildcardMatch`ed keys desired in #247 too.

**Comment by dwarthen-tnn** [comment]
> Hi @dwarthen-tnn, thanks for reporting this. The error that you're seeing (`TypeError: kp.slice is not a function`) is because the package doesn't currently support any RegExps in the `keys` option. As noted in the README, the `keys` option currently just supports either an array of strings or objects in this format:

I think my confusion arose because VS code was assuring me that RegExp was a valid type for the field property, but today I'm not able to replicate that or find any place in the types definitions where that could have come from. 

> If I'm understanding your use case correctly, you're essentially looking for a way to specify a custom title for some keys while still including all of the auto-detected keys in the generated CSV. Is that accurate? 

Yes, that's essentially it. I've worked around this on my end by changing the titles of those fields in my code before they reach the Converter. Not ideal for my use case but it works OK.

Thank you for your reply!
