### ISSUE TITLE
Sync versions aren't present in the module

### ISSUE THREAD

**Issue by bogas04** [mrodrig/json-2-csv#29]
json2csvSync, csv2jsonSync are absent in this module. 
I haven't worked with Promises, but if anybody can give me slight idea, I am willing to take this up.

**Comment by mrodrig** [comment]
Hi @bogas04 .  Sorry for the confusion. I set the module up such that the synchronous functions are accessible at json2csv and csv2json.  The module by default does not include asynchronous versions of the functions, but it is promisifiable.  For example, if you wanted to use the asynchronous versions, you would need to do something like this:

var promise = require ('bluebird'),
      converter = promise.promisifyAll (require ('json-2-csv'));

converter.json2csv (...); // Synchronous
converter.json2csvAsync (...)
      .then (...); // Asynchronous

Sorry for the poor formatting - I'm responding via my phone right now.

Hope this helps!

**Comment by mrodrig** [comment]
I'm going to close this for now since it seems like this might be resolved.  If you have any other questions, don't hesitate to ask.  Thanks!
