### ISSUE TITLE
potential bug: empty value in input where 0 expected

### ISSUE THREAD

**Issue by kurttheviking** [mrodrig/json-2-csv#4]
I am not sure if this is expected behavior or a bug, so I am submitting it for further consideration. Any guidance is much appreciated!
### Setup

Running node 0.10.26, json-2-csv 0.1.4:

```
var converter = require('json-2-csv');

var data = [
  {
    label: 'first',
    value: 10
  },
  {
    label: 'second',
    value: 0
  },
  {
    label: 'third',
    value: 20
  }
];

converter.json2csv(data, function (err, csv) {
  console.log(csv);
});
```
### Observed

```
label,value
first,10
second,
third,20
```
### Expected

```
label,value
first,10
second,0
third,20
```

Note that the expected output contains a `0` on the line associated with the label `second` as provided in the input data.
### Cause?

This appears to be caused by a [`value || ''`](https://github.com/mrodrig/json-2-csv/blob/fac7f7e4b3e5b94982362ee560e41436ea78f7a8/lib/json-2-csv.js#L54) check and `0` evaluates to falsy.

**Comment by thohag** [comment]
Seems like this bug is back (using 1.3.0).
