### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' ./constants

### ISSUE THREAD

**Issue by SBUtltmedia** [mrodrig/json-2-csv#51]
Hi. I installed ```json-2-csv``` through npm and I'm getting this error when I try to build my project using webpack:

```
ERROR in ./~/json-2-csv/lib/converter.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./constants in node_modules/json-2-csv/lib
 @ ./~/json-2-csv/lib/converter.js 5:16-38
```
Any help would be appreciated. Thanks.

**Comment by mrodrig** [comment]
I haven't used webpack before, but I'm definitely willing to look into it.  So far, I created a VM which I'm trying to replicate the issue on.  I installed webpack (via npm install webpack -g), but haven't been able to get the same error.  If you could put together a quick example that gives the error you pasted above, I will definitely take a look at it.

Thanks!

**Comment by mrodrig** [comment]
In fixing another issue, I added the '.json' suffix where the constants file was required in.  This should be up in 2.0.6 on NPM.  Could you check to see if that perhaps fixed the issue?  If not, please let me know.

Thanks!

**Comment by SBUtltmedia** [comment]
Thank you. I added the .json suffix in two other files and it works now. I opened a pull request: https://github.com/mrodrig/json-2-csv/pull/53

**Comment by mrodrig** [comment]
Awesome, I'm glad to hear that adding .json fixed the issue. I just pushed these changes up in the 2.0.7 release.  Thanks!
