### ISSUE TITLE
Capital case?

### ISSUE THREAD

**Issue by adius** [mrodrig/json-2-csv#62]
Why the hell are the keys in the options object written in capital letters. No need to shout (and shitty to type!)

**Comment by mrodrig** [comment]
I guess it was a design choice that I made when starting out with the module. The hard part about changing it now is that the change would have to be backwards compatible (still allow the upper case versions). I'll definitely take a look at fixing it. Thanks!

**Comment by adius** [comment]
Well you can always increment by a major version number and make backwards incompatible changes…
but having lower and upper simultaneously for the beginning sounds like a good idea.

**Comment by mrodrig** [comment]
This should be all set in `2.0.17`. I updated the documentation to have the lower case option keys. Sorry that it took so long - I had a lot of school work going on.  Thanks again for letting me know about this!

**Comment by adius** [comment]
Looks good! Thanks! 👍
