### ISSUE TITLE
Don't throw Rejection Error

### ISSUE THREAD

**Issue by adius** [mrodrig/json-2-csv#63]
Why does it not simple use the superset which contains all fields of all objects use as the table schema instead of throwing the useless error `Unhandled rejection Error: Not all documents have the same schema` ? …or at least provide a flag to do so.

**Comment by mrodrig** [comment]
Thanks for opening this @adius! I must have forgotten to include the "CHECK_SCHEMA_DIFFERENCES" option when I worked on cleaning up the documentation.  If you set `options.CHECK_SCHEMA_DIFFERENCES` to `true`, then it will go through and convert the JSON regardless of whether the documents have the same schema or not.
