### ISSUE TITLE
Last version (converting values with toLocaleString) issue with Numbers

### ISSUE THREAD

**Issue by arenoux** [mrodrig/json-2-csv#66]
Hello.
The last update you made to convert values with `.toLocaleString` will break some existing code...

Although it could be interesting to convert values based on local, maybe you should not have release it as a simple patch (2.0.**15**)...

For example, if you try to convert the following JSON into CSV :
```
{
  key:"key",
  value:1000
}
```
Before 2.0.15, result was:
```
KEY,VALUE
key,1000
```
Since 2.0.15, we will obtain:
```
KEY,VALUE
key,1,000
```

**Comment by mrodrig** [comment]
I apologize for the inconvenience this caused.  I didn't see this on my Cloud9 development machine and therefore didn't realize that change would end up breaking the intended functionality.  The change from #64 is reverted in `2.0.18` and I unpublished all versions containing the `.toLocaleString()` on NPM.  Thank you for reporting this and sorry for the inconvenience.
