### ISSUE TITLE
Promisify it

### ISSUE THREAD

**Issue by pasqLisena** [mrodrig/json-2-csv#82]
It would be nice to make the library return a Promise.

This is not in contrast with the possibility of having a _traditional_ callback.

**Comment by mrodrig** [comment]
Hi @pasqLisena. Sorry for the delay in getting back to you. I've released version `2.2.0` which will include the `json2csvPromisified` and `csv2jsonPromisified` functions which provide the promisified versions of the functions in the module.  Thanks for reporting this!

**Comment by mrodrig** [comment]
`v3.0.0` is out, and while the `json2csvPromisified` named function will still work, I've deprecated it in favor of changing the name to `json2csvAsync`. Hopefully this won't be too much of an inconvenience for people to change when upgrading to `v3.0.0`
