### ISSUE TITLE
Overhaul test setup.

### ISSUE THREAD

**Issue by mrodrig** [mrodrig/json-2-csv#84]
* Convert to promise chains instead of using `async`
* Add additional tests.

**Comment by mrpassiontea** [comment]
May I ask why you'd want to convert to promise chains instead of async?

**Comment by mrpassiontea** [comment]
@mrodrig Just my thinking, maybe you wrote this in order to have more control over your promise.resolves and rejects? Nonetheless, I personally prefer the way async works.

I like the project as it's something I actually need right now.

**Comment by mrodrig** [comment]
@mrpassiontea Thanks! Glad to hear that it's helpful!

I was thinking about it a little more last night and I think the reason may have been to remove it as a devDependency since it's only being used in one spot and the module is already pulling bluebird in for promises. It's one less module to keep up-to-date periodically, but to be honest I probably won't end up removing it.

**Comment by mrodrig** [comment]
Closing this since new tests will be added during the 3.0.0 module update and this may be addressed then, however, the current test setup has been pretty reliable, so I don't really see any reason to change it.
