### ISSUE TITLE
Escape nested quote with an additional quote

### ISSUE THREAD

**Issue by eric-thelin** [mrodrig/json-2-csv#88]
According to [RFC 4180](https://tools.ietf.org/html/rfc4180) the proper way to escape double-quotes in CSV data is to prepend an additional double-quote character:

> If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.

Currently we escape double-quotes using a backslash. Opening a file witch such content in Microsoft Excel and/or Apple Numbers breaks the column layout, i.e. the value containing the double quote is interpretted as multiple columns instead of one. On the contrary, escaping using an extra double-quote preserves the expected column layout in both Microsoft Excel and Apple Numbers.

**Comment by eric-thelin** [comment]
There is a fix available for this issue in pull request #87.

**Comment by mrodrig** [comment]
Thanks! Just published this in 2.3.0.

**Comment by eric-thelin** [comment]
Super! Thanks!
