### ISSUE TITLE
What is the CSV format for nested arrays

### ISSUE THREAD

**Issue by simonh1000** [mrodrig/json-2-csv#9]
I am interested to add functionality to support nested arrays when converting to CSV. I can get the headers with the dot-notation but I'm not sure how to structure the data itself - if I just flatten everything I'm not sure that the data will be re-encodable faithfully. Do you have any specifications for this as I can't find anything on the web easily.

**Comment by mrodrig** [comment]
To be honest, I'm not sure.  I posted on StackOverflow in case someone that has more experience with CSV knows.  The link is: http://stackoverflow.com/questions/27734154/nested-array-values-how-do-they-convert-to-csv

**Comment by mrodrig** [comment]
It sounds like there is no specific way that it needs to be handled.  I believe the converter currently flattens nested arrays into one array which isn't ideal if a user needs to be able to convert back to JSON.  If there's another way that you can think of that is better, I'd definitely be willing to take a look.  Thanks!

**Comment by simonh1000** [comment]
That's basically where I go stuck before, and decided to switch xml
