### ISSUE TITLE
Use case emptyFieldValue

### ISSUE THREAD

**Issue by joostdebruijn** [mrodrig/json-2-csv#97]
## Background Information
- Module Version: `3.0.0`
- Node/Browser Version: ` 11.6.0`

The issue I'm reporting is with:
- [x] json2csv
- [ ] csv2json

I have...
- [x] searched to see if an issue has already been reported.
- [x] verified that my JSON/CSV data is valid (using something like http://jsonlint.com or https://csvlint.io/).
- [x] tried upgrading to the latest version of json-2-csv (since the issue may already be fixed).

## Actual Behavior
In 3.x the emptyFieldValue is removed. The upgrade guide says "Please open an issue on the GitHub repository mrodrig/json-2-csv if you have a valid use case for this option to be implemented.", so here it is!

## Expected Behavior
We use the json2csv function for exporting data from a database to CSV for end-user purposes. End-users mostly use those CSV's in Excel. Previously we used the option emptyFieldValue with the value `''` to replace values like `null` to an empty field in the CSV. In 3.0.0 those fields are now filled with `null`, that could be relevant when converting it back to json, but not for end-user display.

**Comment by mrodrig** [comment]
Hi @joostdebruijn - I pushed out version `3.1.0` which will have the `emptyFieldValue` option added in. Please let me know if you run into any issues with it or if there are any other issues that you run into with the module.

Thanks!

**Comment by joostdebruijn** [comment]
Thanks for the very quick resolution! It works fine now, however at src/utils.js:138 there is a console.log that logs all values to the console. I think that should be removed.

**Comment by mrodrig** [comment]
@joostdebruijn Sorry for the console log sneaking through. I merged your fix and added `no-console` to the linter so it won't happen again. Both are released in `3.1.1` on NPM. Thanks!
